LokeshwarPrasad3/Budgetter-Webapp

client/package-lock.json
client/package.json
client/src/components/header/TopHeader.tsx
client/src/components/hooks/HeaderName.ts
client/src/components/ui/avatar.tsx
client/src/components/ui/collapsible.tsx
client/src/components/ui/label.tsx
client/src/components/user/dashbaord/charts/CategoryWiseExpensesChart.tsx
client/src/pages/user/Profile/ProfilePage.tsx
client/src/routes/routes.tsx

[x] Fixed console error key-props
[x] Added Profile page responsive ui
[x] installed shadcn 
- label
- collapsible
- avatar
[x] fixed some ui issue

Added Profile Page UI

---

client/src/components/auth/ForgotPasswordSection.tsx
client/src/components/auth/LoginSection.tsx
client/src/components/auth/ResetPassword.tsx
client/src/components/auth/SignupSection.tsx
client/src/components/header/TopHeader.tsx
client/src/components/navbar/SideNavbar.tsx
client/src/pages/MainLayout.tsx
client/src/services/auth.ts
server/src/controllers/user.controllers.js
server/src/routes/user.routes.js

[x] Added change password feature by adding password , confirm password
[x] Added notification popover

Api handling

---

client/src/components/auth/AuthHeader.tsx
client/src/components/auth/ForgotPasswordSection.tsx
client/src/components/auth/LoginSection.tsx
client/src/components/auth/ResetPassword.tsx
client/src/components/auth/SignupSection.tsx
client/src/components/header/TopHeader.tsx
client/src/components/home/Features.tsx
client/src/components/home/HeroSection.tsx
client/src/components/home/SocialMedia.tsx
client/src/components/navbar/Navbar.tsx
client/src/components/navbar/SideNavbar.tsx
client/src/pages/MainLayout.tsx
client/src/pages/home/HomePage.tsx
client/src/pages/user/Loader/DashboardLoader.tsx
client/src/pages/user/Loader/SideNavbarLoader.tsx
client/src/pages/user/Loader/TopHeaderLoader.tsx
client/src/pages/user/UserLayout.tsx
client/src/pages/user/addExpenses/AddExpenses.tsx
client/src/pages/user/addMoney/AddMoney.tsx
client/src/pages/user/dashboard/Dashboard.tsx
client/src/pages/user/reports/Reports.tsx
client/src/pages/user/showExpenses/ShowExpenses.tsx

[x] Added types on functional component React.FC
[x] Added types of states

Added Types to Funcational Component and States

---

client/src/components/auth/AccountAlreadyVerified.tsx
client/src/components/auth/LoginSection.tsx
client/src/components/auth/SignupSection.tsx
client/src/components/user/addExpenses/FilterSection.tsx
client/src/components/user/addExpenses/table/UserExpenseTable.tsx
client/src/components/user/dashbaord/SummarizeBoxes.tsx
client/src/components/user/reports/table/AllExpensesTable.tsx
client/src/components/user/showExpenses/table/UserHistoryExpenseTable.tsx
client/src/pages/user/reports/Reports.tsx
client/src/routes/routes.tsx
client/src/services/auth.ts
client/src/services/expenses.ts
client/src/styles/global.css
client/src/utils/date/date.ts
server/src/controllers/expenses.controller.js
server/src/controllers/user.controllers.js
server/src/middleware/auth.middleware.js

[x] Added login by username feature
[x] Added Show all expenses in report page
[x] Added Filter ui in report page
[x] If user verified then show user already verified

Added Show all expenses in report page

---

client/src/components/user/addExpenses/FilterSection.tsx
client/src/pages/user/dashboard/Dashboard.tsx

[x] Added value attribute to reset form after adding expense ( issue 23 )

fix: reset form inputs after add expense

---

client/src/components/user/reports/table/AllExpensesTable.tsx
client/src/styles/global.css

Modify the font of Loading, make the "No Expenses Found" not show up during Loading state

Update Feat: Add Loading Effect

---

client/src/components/user/dashbaord/SummarizeBoxes.tsx
client/src/components/user/dashbaord/charts/CategoryWiseExpensesChart.tsx
client/src/components/user/dashbaord/charts/CategoryWiseLineChart.tsx
client/src/components/user/dashbaord/charts/Loader/DonutChartLoader.tsx
client/src/components/user/reports/table/AllExpensesTable.tsx
client/src/pages/user/dashboard/Dashboard.tsx
client/src/styles/global.css

[x] Added Loader for summarize box in dashboard 
[x] Added Animate loader for category wise expenses donut chart
[x] Fixed double loading.. show in reports all expenses
[x] Added custom css conic gradient and format code

Feat - Add Loader in dashboard summarize box and category-wise chart

---

client/src/components/auth/LoginSection.tsx
client/src/components/auth/SignupSection.tsx
client/src/features/user/user.ts
client/src/pages/MainLayout.tsx
client/src/pages/user/Profile/ProfilePage.tsx
client/src/services/auth.ts
server/src/controllers/user.controllers.js
server/src/middleware/auth.middleware.js
server/src/models/user.model.js
server/src/routes/user.routes.js

[x] Added Username, Email is not editable
[x] User can update their password also
[x] User can update basic details
[x] Added API for update details
[x] Integrated API with UI

Added API to update profile details, Integrated with Frontend

---

client/src/components/user/dashbaord/charts/CategoryWiseExpensesChart.tsx

I am creating a new PR after fixing all. I am new to contributions, so I made a lot of mistakes. I apologize for it and thank you for your support. Let me know if I still miss something.  closes #34

Add percentage values to the donut chart

---

client/src/components/user/reports/table/AllExpensesTable.tsx
client/src/pages/user/dashboard/Dashboard.tsx
client/src/utils/date/date.ts

[x] Added Last 7 days filters
[x] Added month wise filters
[x] Added Total results values

Added Filters functionality in reports page

---

client/package-lock.json
client/package.json
client/src/components/header/TopHeader.tsx
client/src/components/navbar/SideNavbar.tsx

Added Tour Guide for user

---

client/package-lock.json
client/package.json
client/src/components/auth/ForgotPasswordSection.tsx
client/src/components/auth/LoginSection.tsx
client/src/components/auth/ResetPassword.tsx
client/src/components/auth/SignupSection.tsx
client/src/components/navbar/SideNavbar.tsx
client/src/features/sideNavbar/sideNavbarSlice.ts
client/src/pages/auth/AuthLayout.tsx
client/src/pages/user/Loader/DashboardLoader.tsx
client/src/schemas/index.tsx

[x] Fixed when clicked to sidebar menu then its not close ( issue #42  )
[x] Fixed User Data Loading issue after a day ( Fixed JWT expired issue ) ( issue #45 )
[x]Added Formik form handling and Yup form input validation for ( issue #46 )
1. Login page
2. Signup page
3. Reset password page
4. Forgot password page
[x] Enhanced User Details Loader UI
**Please check this PR and close issues no #42 #45 #46**

Added auth form vaidation using formik and yup with fixed some issues

---

client/src/components/user/reports/table/AllExpensesTable.tsx
server/public/email-template/account-delete.html
server/src/controllers/user.controllers.js
server/src/models/deletedUser.model.js
server/src/routes/user.routes.js
server/src/utils/EmailSend.js

[x] Fixed all months , years report filtering issue
[x] Implemented Deleted User data modeling
[x] Implemented Delete User API with email sent
[x] Added Delete User email templates

Implemented feature API for delete user

---

client/.gitignore
client/src/components/auth/ForgotPasswordSection.tsx
client/src/components/auth/LoginSection.tsx
client/src/components/auth/ResetPassword.tsx
client/src/components/header/TopHeader.tsx
client/src/components/layout/UserTourGuide.tsx
client/src/components/navbar/SideNavbar.tsx
client/src/components/user/addExpenses/FilterSection.tsx
client/src/components/user/addMoney/AddMoneySection.tsx
client/src/features/user/user.ts
client/src/pages/user/Profile/ProfilePage.tsx
client/src/pages/user/dashboard/Dashboard.tsx
client/src/services/api.ts
client/src/services/auth.ts

The PR's contains : 
[x] Fixed #47 User Tour guide functionality issues
[x] Added .env file for credentials
[x] Remove unnecessary console

Fixed user-tour function issues and added .env

---

client/package-lock.json
client/package.json
client/src/components/auth/LoginSection.tsx
client/src/components/header/TopHeader.tsx
client/src/components/ui/dialog.tsx
client/src/pages/user/Profile/DeleteAccountDIalog.tsx
client/src/pages/user/Profile/ProfilePage.tsx
client/src/services/auth.ts
client/src/styles/global.css
server/src/app.js
server/src/controllers/user.controllers.js
server/src/routes/user.routes.js

**Solved issue of #48**
[x] Implemented User account delete feature ui  with proper dialog
[x] Implemented API - integration for account delete
[x] updated design of profile page better 
[x] updated top header some classess
[x] fixed some login input password eye icon issue
[x] Updated CORS urls
[x] Implemented API for get all users list

Implemented User account delete feature

---

client/package-lock.json
client/src/components/user/addExpenses/FilterSection.tsx
client/src/routes/routes.tsx

[x] Fixed input responsiveness issue #43 in add expenses page
[x] Fixed route validation issue #41

Fixed UI issues of responsiveness and validation routes

---

server/src/controllers/user.controllers.js
server/src/models/user.model.js
server/src/routes/user.routes.js

Reverts LokeshwarPrasad3/Budgetter-Webapp#58

Revert "Implemented API for add lent money, received lent money, show all len…"

---

client/package-lock.json
client/package.json
client/src/components/auth/GoogleAuthLogin.tsx
client/src/components/auth/LoginSection.tsx
client/src/components/auth/SignupSection.tsx
client/src/components/navbar/SideNavbar.tsx
client/src/main.tsx
client/src/services/auth.ts
server/package-lock.json
server/package.json
server/src/controllers/user.controllers.js
server/src/models/user.model.js
server/src/routes/user.routes.js
server/src/utils/utilities.js

This PR's contains
[x] Implemented Google Auth0 Feature
[x] Implemented backend data store data

Feature Implemented Google Auth Login

---

client/src/pages/user/dashboard/Dashboard.tsx
client/src/services/reports.ts
client/src/utils/date/date.ts
server/src/controllers/expenses.controller.js
server/src/controllers/reports.controllers.js
server/src/controllers/user.controllers.js

This PR's contains Fixing issue #74 
**Backend**:
- Fixed bcrypt issue during login (`this.password` was undefined).
- Updated the API to accept both **year** and **month** as filter arguments.
**Frontend**:
- Implemented dropdowns for selecting **year** and **month**, with API integration.
- Updated state management to filter data and display updated graphs.

Implemented Report Filter in Dashborad page

---

client/src/components/user/PDFExportComponent.tsx
client/src/components/user/reports/table/AllExpensesTable.tsx
client/src/components/user/showExpenses/table/UserHistoryExpenseTable.tsx
client/src/pages/user/dashboard/Dashboard.tsx
client/src/utils/date/date.ts

This PR's contains
[x] Implemented download pdf for report table page

Implemented feature download data in pdf in report page

---

client/package.json
client/src/components/admin/NewsLetter/CodeEditor.tsx
client/src/components/admin/NewsLetter/PreviewBox.tsx
client/src/components/admin/NewsLetter/UploadForm.tsx
client/src/components/hooks/HeaderName.ts
client/src/data/AdminSidebarList.ts
client/src/pages/admin/AdminLayout.tsx
client/src/pages/admin/NewsLetter/NewsletterUpload.tsx
client/src/routes/routes.tsx
client/src/services/adminAccess.ts
client/src/utils/utility.ts
server/package.json
server/public/email-template/account-delete.html
server/public/email-template/account-verification.html
server/public/email-template/reset-password-template.html
server/src/app.js
server/src/controllers/reports.controllers.js
server/src/controllers/user.controllers.js
server/src/routes/user.routes.js
server/src/utils/EmailSend.js

Implemented Feature for admin can send newsletter to all users

---

client/src/components/auth/GoogleAuthLogin.tsx
client/src/components/auth/LoginSection.tsx
client/src/components/auth/SignupSection.tsx
client/src/components/ui/dialog.tsx
client/src/components/user/dashbaord/SummarizeBoxes.tsx
client/src/components/user/dashbaord/actions/view-expenses/ViewCategoryExpensesDialog.tsx
client/src/components/user/dashbaord/table/CategoryInsightsTable.tsx
client/src/components/user/dashbaord/table/useCategoryStats.tsx
client/src/pages/MainLayout.tsx
client/src/pages/user/Profile/ProfilePage.tsx
client/src/types/api/auth/auth.ts
server/src/controllers/user.controllers.js
server/src/models/user.model.js

This PR includes : 
Commit 1 : In dashboard section Categorized Expense Stats :  #84 feature
[x] User can view full view expenses table click on eye button of column
Commit 2 : In User Profile : #71 feature
[x] User can now see their member since
[x] Last active login date

Feat : Implemented view of expenses by category and user member since date & last active date 

---

.husky/pre-commit
client/src/components/auth/GoogleAuthLogin.tsx
client/src/components/auth/LoginSection.tsx
client/src/components/auth/SignupSection.tsx
client/src/components/header/TopHeader.tsx
client/src/components/hooks/HeaderName.ts
client/src/components/navbar/SideNavbar.tsx
client/src/components/profile/sessions/DeleteAllSession.tsx
client/src/components/profile/sessions/SessionsCard.tsx
client/src/components/profile/sessions/ShowSessions.tsx
client/src/components/theme/theme-animations.ts
client/src/components/ui/popover-form.tsx
client/src/components/ui/theme-toggle-button.tsx
client/src/data/AdminSidebarList.ts
client/src/data/UserSideNavbarList.ts
client/src/hooks/auth/useUserLogout.ts
client/src/index.css
client/src/pages/MainLayout.tsx
client/src/pages/user/Profile/ProfilePage.tsx
client/src/services/auth.ts
client/src/styles/global.css
client/src/types/api/auth/auth.ts
server/package-lock.json
server/package.json
server/src/app.js
server/src/controllers/user.controllers.js
server/src/middleware/auth.middleware.js
server/src/models/user.model.js
server/src/routes/user.routes.js
server/src/services/auth.service.js

- Added `ua-parser-js` dependency for user agent detection.  
- Enabled `trust proxy` in `app.js` for forwarded headers.  
- Refactored authentication flow to use centralized session management.  
- Introduced `createSession` and `createUserAndSendVerification` methods in `auth.service.js`.  
- Added session routes: list, delete one, delete all.  
- Built frontend components for viewing and deleting active sessions.  
- Implemented session tracking (IP, device, last used).  
- Extended user model with `sessions` schema.

feat: implement user session management and active session deletion
